export const labelColors = [
  { name: "Gray", classes: "bg-gray-400 dark:bg-gray-700" },
  { name: "Red", classes: "bg-red-400 dark:bg-red-700" },
  { name: "Orange", classes: "bg-orange-400 dark:bg-orange-700" },
  { name: "Amber", classes: "bg-amber-400 dark:bg-amber-700" },
  { name: "Yellow", classes: "bg-yellow-400 dark:bg-yellow-700" },
  { name: "Lime", classes: "bg-lime-400 dark:bg-lime-700" },
  { name: "Green", classes: "bg-green-400 dark:bg-green-700" },
  { name: "Emerald", classes: "bg-emerald-400 dark:bg-emerald-700" },
  { name: "Teal", classes: "bg-teal-400 dark:bg-teal-700" },
  { name: "Cyan", classes: "bg-cyan-400 dark:bg-cyan-700" },
  { name: "Sky", classes: "bg-sky-400 dark:bg-sky-700" },
  { name: "Blue", classes: "bg-blue-400 dark:bg-blue-700" },
  { name: "Indigo", classes: "bg-indigo-400 dark:bg-indigo-700" },
  { name: "Violet", classes: "bg-violet-400 dark:bg-violet-700" },
  { name: "Purple", classes: "bg-purple-400 dark:bg-purple-700" },
  { name: "Fuchsia", classes: "bg-fuchsia-400 dark:bg-fuchsia-700" },
  { name: "Pink", classes: "bg-pink-400 dark:bg-pink-700" },
  { name: "Rose", classes: "bg-rose-400 dark:bg-rose-700" },
];
