/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/react-router'
import type {
  CreateServerFileRoute,
  ServerFileRoutesByPath,
} from '@tanstack/react-start/server'
import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AnonRouteImport } from './routes/_anon'
import { Route as AnonIndexRouteImport } from './routes/_anon/index'
import { Route as AnonPricingRouteImport } from './routes/_anon/pricing'
import { Route as AuthWorkspacesIndexRouteImport } from './routes/_auth/workspaces/index'
import { Route as AuthWorkspacesWorkspaceIdSettingsRouteImport } from './routes/_auth/workspaces/$workspaceId/settings'
import { Route as AuthWorkspacesWorkspaceIdProjectsIndexRouteImport } from './routes/_auth/workspaces/$workspaceId/projects/index'
import { Route as AuthWorkspacesWorkspaceIdProjectsProjectIdIndexRouteImport } from './routes/_auth/workspaces/$workspaceId/projects/$projectId/index'
import { Route as AuthWorkspacesWorkspaceIdProjectsProjectIdSettingsRouteImport } from './routes/_auth/workspaces/$workspaceId/projects/$projectId/settings'
import { Route as AuthWorkspacesWorkspaceIdProjectsProjectIdTaskIdRouteImport } from './routes/_auth/workspaces/$workspaceId/projects/$projectId/$taskId'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'

const rootServerRouteImport = createServerRootRoute()

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnonRoute = AnonRouteImport.update({
  id: '/_anon',
  getParentRoute: () => rootRouteImport,
} as any)
const AnonIndexRoute = AnonIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnonRoute,
} as any)
const AnonPricingRoute = AnonPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AnonRoute,
} as any)
const AuthWorkspacesIndexRoute = AuthWorkspacesIndexRouteImport.update({
  id: '/workspaces/',
  path: '/workspaces/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthWorkspacesWorkspaceIdSettingsRoute =
  AuthWorkspacesWorkspaceIdSettingsRouteImport.update({
    id: '/workspaces/$workspaceId/settings',
    path: '/workspaces/$workspaceId/settings',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthWorkspacesWorkspaceIdProjectsIndexRoute =
  AuthWorkspacesWorkspaceIdProjectsIndexRouteImport.update({
    id: '/workspaces/$workspaceId/projects/',
    path: '/workspaces/$workspaceId/projects/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthWorkspacesWorkspaceIdProjectsProjectIdIndexRoute =
  AuthWorkspacesWorkspaceIdProjectsProjectIdIndexRouteImport.update({
    id: '/workspaces/$workspaceId/projects/$projectId/',
    path: '/workspaces/$workspaceId/projects/$projectId/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthWorkspacesWorkspaceIdProjectsProjectIdSettingsRoute =
  AuthWorkspacesWorkspaceIdProjectsProjectIdSettingsRouteImport.update({
    id: '/workspaces/$workspaceId/projects/$projectId/settings',
    path: '/workspaces/$workspaceId/projects/$projectId/settings',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthWorkspacesWorkspaceIdProjectsProjectIdTaskIdRoute =
  AuthWorkspacesWorkspaceIdProjectsProjectIdTaskIdRouteImport.update({
    id: '/workspaces/$workspaceId/projects/$projectId/$taskId',
    path: '/workspaces/$workspaceId/projects/$projectId/$taskId',
    getParentRoute: () => AuthRoute,
  } as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/pricing': typeof AnonPricingRoute
  '/': typeof AnonIndexRoute
  '/workspaces': typeof AuthWorkspacesIndexRoute
  '/workspaces/$workspaceId/settings': typeof AuthWorkspacesWorkspaceIdSettingsRoute
  '/workspaces/$workspaceId/projects': typeof AuthWorkspacesWorkspaceIdProjectsIndexRoute
  '/workspaces/$workspaceId/projects/$projectId/$taskId': typeof AuthWorkspacesWorkspaceIdProjectsProjectIdTaskIdRoute
  '/workspaces/$workspaceId/projects/$projectId/settings': typeof AuthWorkspacesWorkspaceIdProjectsProjectIdSettingsRoute
  '/workspaces/$workspaceId/projects/$projectId': typeof AuthWorkspacesWorkspaceIdProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/pricing': typeof AnonPricingRoute
  '/': typeof AnonIndexRoute
  '/workspaces': typeof AuthWorkspacesIndexRoute
  '/workspaces/$workspaceId/settings': typeof AuthWorkspacesWorkspaceIdSettingsRoute
  '/workspaces/$workspaceId/projects': typeof AuthWorkspacesWorkspaceIdProjectsIndexRoute
  '/workspaces/$workspaceId/projects/$projectId/$taskId': typeof AuthWorkspacesWorkspaceIdProjectsProjectIdTaskIdRoute
  '/workspaces/$workspaceId/projects/$projectId/settings': typeof AuthWorkspacesWorkspaceIdProjectsProjectIdSettingsRoute
  '/workspaces/$workspaceId/projects/$projectId': typeof AuthWorkspacesWorkspaceIdProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_anon': typeof AnonRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_anon/pricing': typeof AnonPricingRoute
  '/_anon/': typeof AnonIndexRoute
  '/_auth/workspaces/': typeof AuthWorkspacesIndexRoute
  '/_auth/workspaces/$workspaceId/settings': typeof AuthWorkspacesWorkspaceIdSettingsRoute
  '/_auth/workspaces/$workspaceId/projects/': typeof AuthWorkspacesWorkspaceIdProjectsIndexRoute
  '/_auth/workspaces/$workspaceId/projects/$projectId/$taskId': typeof AuthWorkspacesWorkspaceIdProjectsProjectIdTaskIdRoute
  '/_auth/workspaces/$workspaceId/projects/$projectId/settings': typeof AuthWorkspacesWorkspaceIdProjectsProjectIdSettingsRoute
  '/_auth/workspaces/$workspaceId/projects/$projectId/': typeof AuthWorkspacesWorkspaceIdProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/pricing'
    | '/'
    | '/workspaces'
    | '/workspaces/$workspaceId/settings'
    | '/workspaces/$workspaceId/projects'
    | '/workspaces/$workspaceId/projects/$projectId/$taskId'
    | '/workspaces/$workspaceId/projects/$projectId/settings'
    | '/workspaces/$workspaceId/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/pricing'
    | '/'
    | '/workspaces'
    | '/workspaces/$workspaceId/settings'
    | '/workspaces/$workspaceId/projects'
    | '/workspaces/$workspaceId/projects/$projectId/$taskId'
    | '/workspaces/$workspaceId/projects/$projectId/settings'
    | '/workspaces/$workspaceId/projects/$projectId'
  id:
    | '__root__'
    | '/_anon'
    | '/_auth'
    | '/_anon/pricing'
    | '/_anon/'
    | '/_auth/workspaces/'
    | '/_auth/workspaces/$workspaceId/settings'
    | '/_auth/workspaces/$workspaceId/projects/'
    | '/_auth/workspaces/$workspaceId/projects/$projectId/$taskId'
    | '/_auth/workspaces/$workspaceId/projects/$projectId/settings'
    | '/_auth/workspaces/$workspaceId/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AnonRoute: typeof AnonRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}
export interface FileServerRoutesByFullPath {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/auth/$': typeof ApiAuthSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/auth/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/auth/$'
  id: '__root__' | '/api/auth/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_anon': {
      id: '/_anon'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AnonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_anon/pricing': {
      id: '/_anon/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AnonPricingRouteImport
      parentRoute: typeof AnonRoute
    }
    '/_anon/': {
      id: '/_anon/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AnonIndexRouteImport
      parentRoute: typeof AnonRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: ''
      fullPath: '/api/auth/$'
      preLoaderRoute: unknown
      parentRoute: typeof rootRouteImport
    }
    '/_auth/workspaces/': {
      id: '/_auth/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AuthWorkspacesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/workspaces/$workspaceId/settings': {
      id: '/_auth/workspaces/$workspaceId/settings'
      path: '/workspaces/$workspaceId/settings'
      fullPath: '/workspaces/$workspaceId/settings'
      preLoaderRoute: typeof AuthWorkspacesWorkspaceIdSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/workspaces/$workspaceId/projects/': {
      id: '/_auth/workspaces/$workspaceId/projects/'
      path: '/workspaces/$workspaceId/projects'
      fullPath: '/workspaces/$workspaceId/projects'
      preLoaderRoute: typeof AuthWorkspacesWorkspaceIdProjectsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/workspaces/$workspaceId/projects/$projectId/$taskId': {
      id: '/_auth/workspaces/$workspaceId/projects/$projectId/$taskId'
      path: '/workspaces/$workspaceId/projects/$projectId/$taskId'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/$taskId'
      preLoaderRoute: typeof AuthWorkspacesWorkspaceIdProjectsProjectIdTaskIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/workspaces/$workspaceId/projects/$projectId/settings': {
      id: '/_auth/workspaces/$workspaceId/projects/$projectId/settings'
      path: '/workspaces/$workspaceId/projects/$projectId/settings'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/settings'
      preLoaderRoute: typeof AuthWorkspacesWorkspaceIdProjectsProjectIdSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/workspaces/$workspaceId/projects/$projectId/': {
      id: '/_auth/workspaces/$workspaceId/projects/$projectId/'
      path: '/workspaces/$workspaceId/projects/$projectId'
      fullPath: '/workspaces/$workspaceId/projects/$projectId'
      preLoaderRoute: typeof AuthWorkspacesWorkspaceIdProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/_anon': {
      id: '/_anon'
      path: ''
      fullPath: ''
      preLoaderRoute: unknown
      parentRoute: typeof rootServerRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: unknown
      parentRoute: typeof rootServerRouteImport
    }
    '/_anon/pricing': {
      id: '/_anon/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: unknown
      parentRoute: typeof rootServerRouteImport
    }
    '/_anon/': {
      id: '/_anon/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: unknown
      parentRoute: typeof rootServerRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/_auth/workspaces/': {
      id: '/_auth/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: unknown
      parentRoute: typeof rootServerRouteImport
    }
    '/_auth/workspaces/$workspaceId/settings': {
      id: '/_auth/workspaces/$workspaceId/settings'
      path: '/workspaces/$workspaceId/settings'
      fullPath: '/workspaces/$workspaceId/settings'
      preLoaderRoute: unknown
      parentRoute: typeof rootServerRouteImport
    }
    '/_auth/workspaces/$workspaceId/projects/': {
      id: '/_auth/workspaces/$workspaceId/projects/'
      path: '/workspaces/$workspaceId/projects'
      fullPath: '/workspaces/$workspaceId/projects'
      preLoaderRoute: unknown
      parentRoute: typeof rootServerRouteImport
    }
    '/_auth/workspaces/$workspaceId/projects/$projectId/$taskId': {
      id: '/_auth/workspaces/$workspaceId/projects/$projectId/$taskId'
      path: '/workspaces/$workspaceId/projects/$projectId/$taskId'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/$taskId'
      preLoaderRoute: unknown
      parentRoute: typeof rootServerRouteImport
    }
    '/_auth/workspaces/$workspaceId/projects/$projectId/settings': {
      id: '/_auth/workspaces/$workspaceId/projects/$projectId/settings'
      path: '/workspaces/$workspaceId/projects/$projectId/settings'
      fullPath: '/workspaces/$workspaceId/projects/$projectId/settings'
      preLoaderRoute: unknown
      parentRoute: typeof rootServerRouteImport
    }
    '/_auth/workspaces/$workspaceId/projects/$projectId/': {
      id: '/_auth/workspaces/$workspaceId/projects/$projectId/'
      path: '/workspaces/$workspaceId/projects/$projectId'
      fullPath: '/workspaces/$workspaceId/projects/$projectId'
      preLoaderRoute: unknown
      parentRoute: typeof rootServerRouteImport
    }
  }
}

declare module './routes/_anon' {
  const createFileRoute: CreateFileRoute<
    '/_anon',
    FileRoutesByPath['/_anon']['parentRoute'],
    FileRoutesByPath['/_anon']['id'],
    FileRoutesByPath['/_anon']['path'],
    FileRoutesByPath['/_anon']['fullPath']
  >

  const createServerFileRoute: CreateServerFileRoute<
    ServerFileRoutesByPath['/_anon']['parentRoute'],
    ServerFileRoutesByPath['/_anon']['id'],
    ServerFileRoutesByPath['/_anon']['path'],
    ServerFileRoutesByPath['/_anon']['fullPath'],
    unknown
  >
}
declare module './routes/_auth' {
  const createFileRoute: CreateFileRoute<
    '/_auth',
    FileRoutesByPath['/_auth']['parentRoute'],
    FileRoutesByPath['/_auth']['id'],
    FileRoutesByPath['/_auth']['path'],
    FileRoutesByPath['/_auth']['fullPath']
  >

  const createServerFileRoute: CreateServerFileRoute<
    ServerFileRoutesByPath['/_auth']['parentRoute'],
    ServerFileRoutesByPath['/_auth']['id'],
    ServerFileRoutesByPath['/_auth']['path'],
    ServerFileRoutesByPath['/_auth']['fullPath'],
    unknown
  >
}
declare module './routes/_anon/pricing' {
  const createFileRoute: CreateFileRoute<
    '/_anon/pricing',
    FileRoutesByPath['/_anon/pricing']['parentRoute'],
    FileRoutesByPath['/_anon/pricing']['id'],
    FileRoutesByPath['/_anon/pricing']['path'],
    FileRoutesByPath['/_anon/pricing']['fullPath']
  >

  const createServerFileRoute: CreateServerFileRoute<
    ServerFileRoutesByPath['/_anon/pricing']['parentRoute'],
    ServerFileRoutesByPath['/_anon/pricing']['id'],
    ServerFileRoutesByPath['/_anon/pricing']['path'],
    ServerFileRoutesByPath['/_anon/pricing']['fullPath'],
    unknown
  >
}
declare module './routes/_anon/index' {
  const createFileRoute: CreateFileRoute<
    '/_anon/',
    FileRoutesByPath['/_anon/']['parentRoute'],
    FileRoutesByPath['/_anon/']['id'],
    FileRoutesByPath['/_anon/']['path'],
    FileRoutesByPath['/_anon/']['fullPath']
  >

  const createServerFileRoute: CreateServerFileRoute<
    ServerFileRoutesByPath['/_anon/']['parentRoute'],
    ServerFileRoutesByPath['/_anon/']['id'],
    ServerFileRoutesByPath['/_anon/']['path'],
    ServerFileRoutesByPath['/_anon/']['fullPath'],
    unknown
  >
}
declare module './routes/api/auth/$' {
  const createFileRoute: CreateFileRoute<
    '/api/auth/$',
    FileRoutesByPath['/api/auth/$']['parentRoute'],
    FileRoutesByPath['/api/auth/$']['id'],
    FileRoutesByPath['/api/auth/$']['path'],
    FileRoutesByPath['/api/auth/$']['fullPath']
  >

  const createServerFileRoute: CreateServerFileRoute<
    ServerFileRoutesByPath['/api/auth/$']['parentRoute'],
    ServerFileRoutesByPath['/api/auth/$']['id'],
    ServerFileRoutesByPath['/api/auth/$']['path'],
    ServerFileRoutesByPath['/api/auth/$']['fullPath'],
    unknown
  >
}
declare module './routes/_auth/workspaces/index' {
  const createFileRoute: CreateFileRoute<
    '/_auth/workspaces/',
    FileRoutesByPath['/_auth/workspaces/']['parentRoute'],
    FileRoutesByPath['/_auth/workspaces/']['id'],
    FileRoutesByPath['/_auth/workspaces/']['path'],
    FileRoutesByPath['/_auth/workspaces/']['fullPath']
  >

  const createServerFileRoute: CreateServerFileRoute<
    ServerFileRoutesByPath['/_auth/workspaces/']['parentRoute'],
    ServerFileRoutesByPath['/_auth/workspaces/']['id'],
    ServerFileRoutesByPath['/_auth/workspaces/']['path'],
    ServerFileRoutesByPath['/_auth/workspaces/']['fullPath'],
    unknown
  >
}
declare module './routes/_auth/workspaces/$workspaceId/settings' {
  const createFileRoute: CreateFileRoute<
    '/_auth/workspaces/$workspaceId/settings',
    FileRoutesByPath['/_auth/workspaces/$workspaceId/settings']['parentRoute'],
    FileRoutesByPath['/_auth/workspaces/$workspaceId/settings']['id'],
    FileRoutesByPath['/_auth/workspaces/$workspaceId/settings']['path'],
    FileRoutesByPath['/_auth/workspaces/$workspaceId/settings']['fullPath']
  >

  const createServerFileRoute: CreateServerFileRoute<
    ServerFileRoutesByPath['/_auth/workspaces/$workspaceId/settings']['parentRoute'],
    ServerFileRoutesByPath['/_auth/workspaces/$workspaceId/settings']['id'],
    ServerFileRoutesByPath['/_auth/workspaces/$workspaceId/settings']['path'],
    ServerFileRoutesByPath['/_auth/workspaces/$workspaceId/settings']['fullPath'],
    unknown
  >
}
declare module './routes/_auth/workspaces/$workspaceId/projects/index' {
  const createFileRoute: CreateFileRoute<
    '/_auth/workspaces/$workspaceId/projects/',
    FileRoutesByPath['/_auth/workspaces/$workspaceId/projects/']['parentRoute'],
    FileRoutesByPath['/_auth/workspaces/$workspaceId/projects/']['id'],
    FileRoutesByPath['/_auth/workspaces/$workspaceId/projects/']['path'],
    FileRoutesByPath['/_auth/workspaces/$workspaceId/projects/']['fullPath']
  >

  const createServerFileRoute: CreateServerFileRoute<
    ServerFileRoutesByPath['/_auth/workspaces/$workspaceId/projects/']['parentRoute'],
    ServerFileRoutesByPath['/_auth/workspaces/$workspaceId/projects/']['id'],
    ServerFileRoutesByPath['/_auth/workspaces/$workspaceId/projects/']['path'],
    ServerFileRoutesByPath['/_auth/workspaces/$workspaceId/projects/']['fullPath'],
    unknown
  >
}
declare module './routes/_auth/workspaces/$workspaceId/projects/$projectId/$taskId' {
  const createFileRoute: CreateFileRoute<
    '/_auth/workspaces/$workspaceId/projects/$projectId/$taskId',
    FileRoutesByPath['/_auth/workspaces/$workspaceId/projects/$projectId/$taskId']['parentRoute'],
    FileRoutesByPath['/_auth/workspaces/$workspaceId/projects/$projectId/$taskId']['id'],
    FileRoutesByPath['/_auth/workspaces/$workspaceId/projects/$projectId/$taskId']['path'],
    FileRoutesByPath['/_auth/workspaces/$workspaceId/projects/$projectId/$taskId']['fullPath']
  >

  const createServerFileRoute: CreateServerFileRoute<
    ServerFileRoutesByPath['/_auth/workspaces/$workspaceId/projects/$projectId/$taskId']['parentRoute'],
    ServerFileRoutesByPath['/_auth/workspaces/$workspaceId/projects/$projectId/$taskId']['id'],
    ServerFileRoutesByPath['/_auth/workspaces/$workspaceId/projects/$projectId/$taskId']['path'],
    ServerFileRoutesByPath['/_auth/workspaces/$workspaceId/projects/$projectId/$taskId']['fullPath'],
    unknown
  >
}
declare module './routes/_auth/workspaces/$workspaceId/projects/$projectId/settings' {
  const createFileRoute: CreateFileRoute<
    '/_auth/workspaces/$workspaceId/projects/$projectId/settings',
    FileRoutesByPath['/_auth/workspaces/$workspaceId/projects/$projectId/settings']['parentRoute'],
    FileRoutesByPath['/_auth/workspaces/$workspaceId/projects/$projectId/settings']['id'],
    FileRoutesByPath['/_auth/workspaces/$workspaceId/projects/$projectId/settings']['path'],
    FileRoutesByPath['/_auth/workspaces/$workspaceId/projects/$projectId/settings']['fullPath']
  >

  const createServerFileRoute: CreateServerFileRoute<
    ServerFileRoutesByPath['/_auth/workspaces/$workspaceId/projects/$projectId/settings']['parentRoute'],
    ServerFileRoutesByPath['/_auth/workspaces/$workspaceId/projects/$projectId/settings']['id'],
    ServerFileRoutesByPath['/_auth/workspaces/$workspaceId/projects/$projectId/settings']['path'],
    ServerFileRoutesByPath['/_auth/workspaces/$workspaceId/projects/$projectId/settings']['fullPath'],
    unknown
  >
}
declare module './routes/_auth/workspaces/$workspaceId/projects/$projectId/index' {
  const createFileRoute: CreateFileRoute<
    '/_auth/workspaces/$workspaceId/projects/$projectId/',
    FileRoutesByPath['/_auth/workspaces/$workspaceId/projects/$projectId/']['parentRoute'],
    FileRoutesByPath['/_auth/workspaces/$workspaceId/projects/$projectId/']['id'],
    FileRoutesByPath['/_auth/workspaces/$workspaceId/projects/$projectId/']['path'],
    FileRoutesByPath['/_auth/workspaces/$workspaceId/projects/$projectId/']['fullPath']
  >

  const createServerFileRoute: CreateServerFileRoute<
    ServerFileRoutesByPath['/_auth/workspaces/$workspaceId/projects/$projectId/']['parentRoute'],
    ServerFileRoutesByPath['/_auth/workspaces/$workspaceId/projects/$projectId/']['id'],
    ServerFileRoutesByPath['/_auth/workspaces/$workspaceId/projects/$projectId/']['path'],
    ServerFileRoutesByPath['/_auth/workspaces/$workspaceId/projects/$projectId/']['fullPath'],
    unknown
  >
}

interface AnonRouteChildren {
  AnonPricingRoute: typeof AnonPricingRoute
  AnonIndexRoute: typeof AnonIndexRoute
}

const AnonRouteChildren: AnonRouteChildren = {
  AnonPricingRoute: AnonPricingRoute,
  AnonIndexRoute: AnonIndexRoute,
}

const AnonRouteWithChildren = AnonRoute._addFileChildren(AnonRouteChildren)

interface AuthRouteChildren {
  AuthWorkspacesIndexRoute: typeof AuthWorkspacesIndexRoute
  AuthWorkspacesWorkspaceIdSettingsRoute: typeof AuthWorkspacesWorkspaceIdSettingsRoute
  AuthWorkspacesWorkspaceIdProjectsIndexRoute: typeof AuthWorkspacesWorkspaceIdProjectsIndexRoute
  AuthWorkspacesWorkspaceIdProjectsProjectIdTaskIdRoute: typeof AuthWorkspacesWorkspaceIdProjectsProjectIdTaskIdRoute
  AuthWorkspacesWorkspaceIdProjectsProjectIdSettingsRoute: typeof AuthWorkspacesWorkspaceIdProjectsProjectIdSettingsRoute
  AuthWorkspacesWorkspaceIdProjectsProjectIdIndexRoute: typeof AuthWorkspacesWorkspaceIdProjectsProjectIdIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthWorkspacesIndexRoute: AuthWorkspacesIndexRoute,
  AuthWorkspacesWorkspaceIdSettingsRoute:
    AuthWorkspacesWorkspaceIdSettingsRoute,
  AuthWorkspacesWorkspaceIdProjectsIndexRoute:
    AuthWorkspacesWorkspaceIdProjectsIndexRoute,
  AuthWorkspacesWorkspaceIdProjectsProjectIdTaskIdRoute:
    AuthWorkspacesWorkspaceIdProjectsProjectIdTaskIdRoute,
  AuthWorkspacesWorkspaceIdProjectsProjectIdSettingsRoute:
    AuthWorkspacesWorkspaceIdProjectsProjectIdSettingsRoute,
  AuthWorkspacesWorkspaceIdProjectsProjectIdIndexRoute:
    AuthWorkspacesWorkspaceIdProjectsProjectIdIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AnonRoute: AnonRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
