/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/react-router'
import type {
  CreateServerFileRoute,
  ServerFileRoutesByPath,
} from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AnonRouteImport } from './routes/_anon'
import { Route as AnonIndexRouteImport } from './routes/_anon/index'
import { Route as AnonPricingRouteImport } from './routes/_anon/pricing'
import { Route as AuthWorkspacesIndexRouteImport } from './routes/_auth/workspaces/index'
import { Route as AuthWorkspacesWorkspaceIdRouteImport } from './routes/_auth/workspaces/$workspaceId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnonRoute = AnonRouteImport.update({
  id: '/_anon',
  getParentRoute: () => rootRouteImport,
} as any)
const AnonIndexRoute = AnonIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnonRoute,
} as any)
const AnonPricingRoute = AnonPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AnonRoute,
} as any)
const AuthWorkspacesIndexRoute = AuthWorkspacesIndexRouteImport.update({
  id: '/workspaces/',
  path: '/workspaces/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthWorkspacesWorkspaceIdRoute =
  AuthWorkspacesWorkspaceIdRouteImport.update({
    id: '/workspaces/$workspaceId',
    path: '/workspaces/$workspaceId',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/pricing': typeof AnonPricingRoute
  '/': typeof AnonIndexRoute
  '/workspaces/$workspaceId': typeof AuthWorkspacesWorkspaceIdRoute
  '/workspaces': typeof AuthWorkspacesIndexRoute
}
export interface FileRoutesByTo {
  '/pricing': typeof AnonPricingRoute
  '/': typeof AnonIndexRoute
  '/workspaces/$workspaceId': typeof AuthWorkspacesWorkspaceIdRoute
  '/workspaces': typeof AuthWorkspacesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_anon': typeof AnonRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_anon/pricing': typeof AnonPricingRoute
  '/_anon/': typeof AnonIndexRoute
  '/_auth/workspaces/$workspaceId': typeof AuthWorkspacesWorkspaceIdRoute
  '/_auth/workspaces/': typeof AuthWorkspacesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/pricing' | '/' | '/workspaces/$workspaceId' | '/workspaces'
  fileRoutesByTo: FileRoutesByTo
  to: '/pricing' | '/' | '/workspaces/$workspaceId' | '/workspaces'
  id:
    | '__root__'
    | '/_anon'
    | '/_auth'
    | '/_anon/pricing'
    | '/_anon/'
    | '/_auth/workspaces/$workspaceId'
    | '/_auth/workspaces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AnonRoute: typeof AnonRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_anon': {
      id: '/_anon'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AnonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_anon/pricing': {
      id: '/_anon/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AnonPricingRouteImport
      parentRoute: typeof AnonRoute
    }
    '/_anon/': {
      id: '/_anon/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AnonIndexRouteImport
      parentRoute: typeof AnonRoute
    }
    '/_auth/workspaces/$workspaceId': {
      id: '/_auth/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof AuthWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/workspaces/': {
      id: '/_auth/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AuthWorkspacesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

declare module './routes/_anon' {
  const createFileRoute: CreateFileRoute<
    '/_anon',
    FileRoutesByPath['/_anon']['parentRoute'],
    FileRoutesByPath['/_anon']['id'],
    FileRoutesByPath['/_anon']['path'],
    FileRoutesByPath['/_anon']['fullPath']
  >

  const createServerFileRoute: CreateServerFileRoute<
    ServerFileRoutesByPath['/_anon']['parentRoute'],
    ServerFileRoutesByPath['/_anon']['id'],
    ServerFileRoutesByPath['/_anon']['path'],
    ServerFileRoutesByPath['/_anon']['fullPath'],
    unknown
  >
}
declare module './routes/_auth' {
  const createFileRoute: CreateFileRoute<
    '/_auth',
    FileRoutesByPath['/_auth']['parentRoute'],
    FileRoutesByPath['/_auth']['id'],
    FileRoutesByPath['/_auth']['path'],
    FileRoutesByPath['/_auth']['fullPath']
  >

  const createServerFileRoute: CreateServerFileRoute<
    ServerFileRoutesByPath['/_auth']['parentRoute'],
    ServerFileRoutesByPath['/_auth']['id'],
    ServerFileRoutesByPath['/_auth']['path'],
    ServerFileRoutesByPath['/_auth']['fullPath'],
    unknown
  >
}
declare module './routes/_anon/pricing' {
  const createFileRoute: CreateFileRoute<
    '/_anon/pricing',
    FileRoutesByPath['/_anon/pricing']['parentRoute'],
    FileRoutesByPath['/_anon/pricing']['id'],
    FileRoutesByPath['/_anon/pricing']['path'],
    FileRoutesByPath['/_anon/pricing']['fullPath']
  >

  const createServerFileRoute: CreateServerFileRoute<
    ServerFileRoutesByPath['/_anon/pricing']['parentRoute'],
    ServerFileRoutesByPath['/_anon/pricing']['id'],
    ServerFileRoutesByPath['/_anon/pricing']['path'],
    ServerFileRoutesByPath['/_anon/pricing']['fullPath'],
    unknown
  >
}
declare module './routes/_anon/index' {
  const createFileRoute: CreateFileRoute<
    '/_anon/',
    FileRoutesByPath['/_anon/']['parentRoute'],
    FileRoutesByPath['/_anon/']['id'],
    FileRoutesByPath['/_anon/']['path'],
    FileRoutesByPath['/_anon/']['fullPath']
  >

  const createServerFileRoute: CreateServerFileRoute<
    ServerFileRoutesByPath['/_anon/']['parentRoute'],
    ServerFileRoutesByPath['/_anon/']['id'],
    ServerFileRoutesByPath['/_anon/']['path'],
    ServerFileRoutesByPath['/_anon/']['fullPath'],
    unknown
  >
}
declare module './routes/_auth/workspaces/$workspaceId' {
  const createFileRoute: CreateFileRoute<
    '/_auth/workspaces/$workspaceId',
    FileRoutesByPath['/_auth/workspaces/$workspaceId']['parentRoute'],
    FileRoutesByPath['/_auth/workspaces/$workspaceId']['id'],
    FileRoutesByPath['/_auth/workspaces/$workspaceId']['path'],
    FileRoutesByPath['/_auth/workspaces/$workspaceId']['fullPath']
  >

  const createServerFileRoute: CreateServerFileRoute<
    ServerFileRoutesByPath['/_auth/workspaces/$workspaceId']['parentRoute'],
    ServerFileRoutesByPath['/_auth/workspaces/$workspaceId']['id'],
    ServerFileRoutesByPath['/_auth/workspaces/$workspaceId']['path'],
    ServerFileRoutesByPath['/_auth/workspaces/$workspaceId']['fullPath'],
    unknown
  >
}
declare module './routes/_auth/workspaces/index' {
  const createFileRoute: CreateFileRoute<
    '/_auth/workspaces/',
    FileRoutesByPath['/_auth/workspaces/']['parentRoute'],
    FileRoutesByPath['/_auth/workspaces/']['id'],
    FileRoutesByPath['/_auth/workspaces/']['path'],
    FileRoutesByPath['/_auth/workspaces/']['fullPath']
  >

  const createServerFileRoute: CreateServerFileRoute<
    ServerFileRoutesByPath['/_auth/workspaces/']['parentRoute'],
    ServerFileRoutesByPath['/_auth/workspaces/']['id'],
    ServerFileRoutesByPath['/_auth/workspaces/']['path'],
    ServerFileRoutesByPath['/_auth/workspaces/']['fullPath'],
    unknown
  >
}

interface AnonRouteChildren {
  AnonPricingRoute: typeof AnonPricingRoute
  AnonIndexRoute: typeof AnonIndexRoute
}

const AnonRouteChildren: AnonRouteChildren = {
  AnonPricingRoute: AnonPricingRoute,
  AnonIndexRoute: AnonIndexRoute,
}

const AnonRouteWithChildren = AnonRoute._addFileChildren(AnonRouteChildren)

interface AuthRouteChildren {
  AuthWorkspacesWorkspaceIdRoute: typeof AuthWorkspacesWorkspaceIdRoute
  AuthWorkspacesIndexRoute: typeof AuthWorkspacesIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthWorkspacesWorkspaceIdRoute: AuthWorkspacesWorkspaceIdRoute,
  AuthWorkspacesIndexRoute: AuthWorkspacesIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AnonRoute: AnonRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
